-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS alumnado.alumnos
(
    id_alumno integer NOT NULL DEFAULT nextval('alumnado.alumnos_id_alumno_seq'::regclass),
    dni integer,
    nombre "char"[] NOT NULL,
    apellido "char"[] NOT NULL,
    id_sexo integer NOT NULL DEFAULT nextval('alumnado.alumnos_id_sexo_seq'::regclass),
    fecha_nacimiento date,
    id_barrio integer NOT NULL DEFAULT nextval('alumnado.alumnos_id_barrio_seq'::regclass),
    id_tipo_domicilio integer NOT NULL DEFAULT nextval('alumnado.alumnos_id_tipo_domicilio_seq'::regclass),
    CONSTRAINT alumnos_pkey PRIMARY KEY (id_alumno)
);

CREATE TABLE IF NOT EXISTS alumnado.barrio
(
    id_barrio integer NOT NULL DEFAULT nextval('alumnado.barrio_id_barrio_seq'::regclass),
    nombre "char"[],
    CONSTRAINT barrio_pkey PRIMARY KEY (id_barrio)
);

CREATE TABLE IF NOT EXISTS alumnado.sexo
(
    id_sexo integer NOT NULL DEFAULT nextval('alumnado.sexo_id_sexo_seq'::regclass),
    descripcion "char"[],
    CONSTRAINT sexo_pkey PRIMARY KEY (id_sexo)
);

CREATE TABLE IF NOT EXISTS alumnado.tipo_domicilio
(
    id_tipo_domicilio integer NOT NULL DEFAULT nextval('alumnado.tipo_domicilio_id_tipo_domicilio_seq'::regclass),
    descripcion "char"[],
    CONSTRAINT tipo_domicilio_pkey PRIMARY KEY (id_tipo_domicilio)
);

CREATE TABLE IF NOT EXISTS alumnado.oferta
(
    id_oferta serial NOT NULL,
    descripcion "char"[],
    oferta_nro integer,
    PRIMARY KEY (id_oferta)
);

CREATE TABLE IF NOT EXISTS alumnado.oferta_alumno
(
    id_oferta_alumno serial NOT NULL,
    id_alumno serial,
    id_oferta serial,
    "año" integer,
    PRIMARY KEY (id_oferta_alumno)
);

CREATE TABLE IF NOT EXISTS alumnado.plan
(
    id_plan serial NOT NULL,
    descripcion "char"[],
    fecha_plan date,
    codigo_plan "char"[],
    PRIMARY KEY (id_plan)
);

CREATE TABLE IF NOT EXISTS alumnado.alumno_plan
(
    id_alumno_plan serial NOT NULL,
    id_alumno serial,
    id_plan serial,
    "año" integer,
    PRIMARY KEY (id_alumno_plan)
);

CREATE TABLE IF NOT EXISTS alumnado.materias
(
    id_materia serial NOT NULL,
    nombre "char"[],
    id_plan integer,
    PRIMARY KEY (id_materia)
);
END;